name: CI

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Lint
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Typecheck
        run: pnpm run typecheck

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build

      - name: Publish snapshot packages
        if: ${{ github.event_name == 'pull_request' }}
        run: >
          ./node_modules/.bin/pkg-pr-new publish --pnpm
          ./packages/*
